 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202557201029;



import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Al
 */
public class FrameLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameLogin.class.getName());
    

    /**
     * Creates new form FrameLogin
     */
    public FrameLogin() {
        initComponents();

//        myDesign();
    }

//    void myDesign() {
//        btnLogin.putClientProperty("FlatLaf.style",
//                "borderWidth:2; "
//                + "arc:15; "
//                + "borderColor:#000000; "
//                + "focusedBorderColor:#000000; "
//                + "hoverBorderColor:#000000"
//        );
//
//        tUsername.putClientProperty(
//                "FlatLaf.style",
//                "borderWidth:2;arc:15;borderColor:#000000; focusedBorderColor:#000000");
//
//        tPassword.putClientProperty(
//                "FlatLaf.style",
//                "borderWidth:2;arc:15;borderColor:#000000; focusedBorderColor:#000000");
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.setMinimumSize(new java.awt.Dimension(540, 720));
        jPanel2.setPreferredSize(new java.awt.Dimension(540, 720));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/pexels-dextarvision-15599167 (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMinimumSize(new java.awt.Dimension(540, 720));
        jLabel5.setPreferredSize(new java.awt.Dimension(540, 720));
        jPanel2.add(jLabel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.WEST);

        jPanel1.setBackground(new java.awt.Color(219, 243, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(740, 720));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Login");

        tUsername.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 14)); // NOI18N
        tUsername.setMargin(new java.awt.Insets(2, 20, 2, 6));

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        tPassword.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tPassword.setMargin(new java.awt.Insets(2, 20, 2, 6));

        btnLogin.setBackground(new java.awt.Color(101, 202, 255));
        btnLogin.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 1, 18)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Close Window.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblClose)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tUsername)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tPassword)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(66, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        //ambil teks yg dimasukkan user pada field username 
        String username = tUsername.getText();
        
        //ambil teks yg dimasukkan user pada field password
        String password = tPassword.getText();
        
        //periksa apakah username dan password tidak kosong
        if (username.length() != 0 && password.length() != 0) {
            try {
                //query sql utk mencari user dengan username dan password di hash dengan MD5
                String sql = "SELECT * FROM user WHERE username=? AND password=md5(?)";
                
                //membuat koneksi ke databse
                Connection con = Koneksi.konek();
                
                //siapkan statement sql dgn paramater
                PreparedStatement ps = con.prepareStatement(sql);
                
                //isi paramter pertama (?) dgn username
                ps.setString(1, username);
                
                //isi paramater kedua (?) dgn password yg akan di hash di md5 di sisi databse
                ps.setString(2, password);
                
                
                //jalankan query dan ambil hasilnya
                ResultSet rs = ps.executeQuery();
                
                //jika hasil query memiliki hasil (berarti login berhasil)
                if (rs.next()) {
                    //tutp form login
                    dispose();
                    
                    //buka form sidebar/dashboard
                    new FrameSidebar().setVisible(true);
                } else {
                    //jika data tdk ditemukan, tampilkan pesan error
                    JOptionPane.showMessageDialog(null, "Username/password salah");
                }
            } catch (SQLException sQLException) {
                //jika terjadi kesalahan sql, tampilkan pesan error
                JOptionPane.showMessageDialog(null, sQLException.getMessage());
            }
        } else {
            //jika username / password kosong, beri peringatan ke user
            JOptionPane.showMessageDialog(null, "Username/password tidak boleh kosong");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            UIManager.put("Button.arc", 10);
            UIManager.put("TextComponent.arc", 10);

            UIManager.put("Button.borderWidth", 1);
            UIManager.put("Component.borderWidth", 1);
            UIManager.put("ComboBox.borderWidth", 1);
            UIManager.put("TextComponent.borderWidth", 1);
            

            UIManager.put("Button.borderColor", java.awt.Color.BLACK);
            UIManager.put("Component.borderColor", java.awt.Color.BLACK);
            UIManager.put("ComboBox.borderColor", java.awt.Color.BLACK);

            UIManager.put("Button.hoverBorderColor", java.awt.Color.BLACK); 
            UIManager.put("ComboBox.hoverBorderColor", java.awt.Color.BLACK);
            UIManager.put("Component.hoverBorderColor", java.awt.Color.BLACK); 

            UIManager.put("Component.focusedBorderColor", java.awt.Color.BLACK);
            UIManager.put("ComboBox.focusedBorderColor", java.awt.Color.BLACK);
            UIManager.put("Button.focusedBorderColor", java.awt.Color.BLACK);

            UIManager.put("Component.focusWidth", 0);
            UIManager.put("ComboBox.focusWidth", 0);

            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables
}
