/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202557201029;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Al
 */
public class FrameSidebar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameSidebar.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form FrameDashboard
     */
    public FrameSidebar() {
        initComponents();
        new JFrame().setSize(1280,720);
        
        inisiasiPanel();
        

    }
    
    void inisiasiPanel(){
        cardLayout = (CardLayout)contentPanel.getLayout();
        contentPanel.add(new PanelDashboard(), "dashboard");
        contentPanel.add(new PanelJurusan(), "jurusan");
        contentPanel.add(new PanelGuru(), "guru");
        contentPanel.add(new PanelKelas(), "kelas");
        contentPanel.add(new PanelSiswa(), "siswa");
        contentPanel.add(new PanelAbout(), "about");
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnJurusan = new javax.swing.JButton();
        btnGuru = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        btnSiswa = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelSidebar.setBackground(new java.awt.Color(219, 243, 255));
        panelSidebar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        panelSidebar.setMinimumSize(new java.awt.Dimension(300, 720));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 720));
        panelSidebar.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(219, 243, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(346, 78));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Student Male.png"))); // NOI18N
        jLabel2.setText("Aloomni");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        panelSidebar.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(219, 243, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 0, 0, 0));

        btnDashboard.setBackground(new java.awt.Color(219, 243, 255));
        btnDashboard.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Speedometer.png"))); // NOI18N
        btnDashboard.setText("Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDashboard.setIconTextGap(20);
        btnDashboard.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnDashboard.setPreferredSize(new java.awt.Dimension(149, 55));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        btnLogout.setBackground(new java.awt.Color(219, 243, 255));
        btnLogout.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Logout Rounded Left.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.setIconTextGap(20);
        btnLogout.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnLogout.setPreferredSize(new java.awt.Dimension(149, 55));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnJurusan.setBackground(new java.awt.Color(219, 243, 255));
        btnJurusan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Building.png"))); // NOI18N
        btnJurusan.setText("Jurusan");
        btnJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJurusan.setIconTextGap(20);
        btnJurusan.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnJurusan.setPreferredSize(new java.awt.Dimension(149, 55));
        btnJurusan.addActionListener(this::btnJurusanActionPerformed);

        btnGuru.setBackground(new java.awt.Color(219, 243, 255));
        btnGuru.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/School Director.png"))); // NOI18N
        btnGuru.setText("Guru");
        btnGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuru.setIconTextGap(20);
        btnGuru.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnGuru.setPreferredSize(new java.awt.Dimension(149, 55));
        btnGuru.addActionListener(this::btnGuruActionPerformed);

        btnKelas.setBackground(new java.awt.Color(219, 243, 255));
        btnKelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Class.png"))); // NOI18N
        btnKelas.setText("Kelas");
        btnKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKelas.setIconTextGap(20);
        btnKelas.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnKelas.setPreferredSize(new java.awt.Dimension(149, 55));
        btnKelas.addActionListener(this::btnKelasActionPerformed);

        btnSiswa.setBackground(new java.awt.Color(219, 243, 255));
        btnSiswa.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Graduation Cap.png"))); // NOI18N
        btnSiswa.setText("Siswa");
        btnSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSiswa.setIconTextGap(20);
        btnSiswa.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnSiswa.setPreferredSize(new java.awt.Dimension(149, 55));
        btnSiswa.addActionListener(this::btnSiswaActionPerformed);

        btnAbout.setBackground(new java.awt.Color(219, 243, 255));
        btnAbout.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Info.png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setIconTextGap(20);
        btnAbout.setMargin(new java.awt.Insets(2, 24, 3, 14));
        btnAbout.setPreferredSize(new java.awt.Dimension(149, 55));
        btnAbout.addActionListener(this::btnAboutActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnJurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(btnGuru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelSidebar.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelSidebar, java.awt.BorderLayout.LINE_START);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.BorderLayout());

        contentPanel.setBackground(new java.awt.Color(173, 227, 255));
        contentPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        contentPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(contentPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1280, 720));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);

        switch (pilihan) {
            case JOptionPane.YES_OPTION:
                dispose();
                new FrameLogin().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "dashboard");
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "jurusan");
    }//GEN-LAST:event_btnJurusanActionPerformed

    private void btnGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "guru");
    }//GEN-LAST:event_btnGuruActionPerformed

    private void btnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "kelas");
    }//GEN-LAST:event_btnKelasActionPerformed

    private void btnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "siswa");
    }//GEN-LAST:event_btnSiswaActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "about");
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //UIManager.put("Button.borderWidth", 0);

        try {
            UIManager.put("Button.borderWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrameSidebar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnGuru;
    private javax.swing.JButton btnJurusan;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSiswa;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
