/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201029;

/**
 *
 * @author Al
 */
public class PanelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jmlJurusan = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jmlGuru = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jmlSiswa = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jmlKelas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 220, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24)));
        setMinimumSize(new java.awt.Dimension(930, 590));
        setPreferredSize(new java.awt.Dimension(830, 720));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(219, 243, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24)));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 24, 0));

        jPanel2.setBackground(new java.awt.Color(219, 243, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel5.setPreferredSize(new java.awt.Dimension(928, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(101, 202, 255));
        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JUMLAH JURUSAN");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel5.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jmlJurusan.setBackground(new java.awt.Color(255, 255, 255));
        jmlJurusan.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 36)); // NOI18N
        jmlJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlJurusan.setText("JJ");
        jmlJurusan.setOpaque(true);
        jPanel5.add(jmlJurusan, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(219, 243, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setPreferredSize(new java.awt.Dimension(928, 150));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(101, 202, 255));
        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("JUMLAH GURU");
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jmlGuru.setBackground(new java.awt.Color(255, 255, 255));
        jmlGuru.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 36)); // NOI18N
        jmlGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlGuru.setText("JG");
        jmlGuru.setOpaque(true);
        jPanel6.add(jmlGuru, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(219, 243, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setPreferredSize(new java.awt.Dimension(928, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(101, 202, 255));
        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JUMLAH SISWA");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel7.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jmlSiswa.setBackground(new java.awt.Color(255, 255, 255));
        jmlSiswa.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 36)); // NOI18N
        jmlSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlSiswa.setText("JS");
        jmlSiswa.setOpaque(true);
        jPanel7.add(jmlSiswa, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel4);

        jPanel8.setBackground(new java.awt.Color(219, 243, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel9.setPreferredSize(new java.awt.Dimension(928, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel7.setBackground(new java.awt.Color(101, 202, 255));
        jLabel7.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("JUMLAH KELAS");
        jLabel7.setOpaque(true);
        jLabel7.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel9.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jmlKelas.setBackground(new java.awt.Color(255, 255, 255));
        jmlKelas.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 36)); // NOI18N
        jmlKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jmlKelas.setText("JK");
        jmlKelas.setOpaque(true);
        jPanel9.add(jmlKelas, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel8);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jmlGuru;
    private javax.swing.JLabel jmlJurusan;
    private javax.swing.JLabel jmlKelas;
    private javax.swing.JLabel jmlSiswa;
    // End of variables declaration//GEN-END:variables
}
