/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201029;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Al
 */
public class PanelJurusan extends javax.swing.JPanel {
    
    

    /**
     * Creates new form PanelDashboard
     */
    public PanelJurusan() {
        initComponents();
        reset();
        load_tabel_jurusan();
    }

    void reset() {
        // Kosongkan isi text field kode jurusan
        tKodeJur.setText(null);

        // Aktifkan kembali text field kode jurusan agar bisa diedit
        tKodeJur.setEditable(true);

        // Kosongkan isi text field nama jurusan
        tNamaJur.setText(null);

    }

    void load_tabel_jurusan() {
        //membuat objek model tabel baru
        DefaultTableModel model = new DefaultTableModel();
        
        //menambahkan kolom ke dalam model tabel
        
        // kolom pertama utk kode jurusan
        model.addColumn("Kode Jurusan");
        // kolom pertama utk nama jurusan
        model.addColumn("Nama Jurusan");
        
        // Query SQL untuk mengambil semua data dari tabel jurusan
        String sql = "SELECT * FROM jurusan";

        try {
            // Membuka koneksi ke database
            Connection conn = Koneksi.konek();
            
            // Membuat statement untuk menjalankan query
            Statement st = conn.createStatement();
            
            // Menjalankan query dan menyimpan hasilnya dalam ResultSet
            ResultSet rs = st.executeQuery(sql);
            
            // Melakukan iterasi untuk setiap baris data hasil query
            while (rs.next()) {
                // Mengambil data kolom kode_jur
                String kodeJurusan = rs.getString("kode_jur");
                
                // Mengambil data kolom nama_jur
                String namaJurusan = rs.getString("nama_jur");
                
                // Membuat array berisi data satu baris
                Object[] baris = {kodeJurusan, namaJurusan};
                
                // Menambahkan array baris ke dalam model tabel
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            // Menampilkan pesan error jika gagal mengambil data dari database
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
        
        // Menampilkan model yang sudah diisi ke dalam tabel GUI
        tblJurusan.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tKodeJur = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNamaJur = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 220, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24)));
        setMinimumSize(new java.awt.Dimension(930, 590));
        setPreferredSize(new java.awt.Dimension(930, 590));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(219, 243, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(101, 202, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText("Data Jurusan");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 24, 0, 0));
        jPanel10.add(jLabel1);

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Close Window.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 24));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel10.add(lblClose);

        jPanel1.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(219, 243, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 0, 24));
        jPanel3.setMinimumSize(new java.awt.Dimension(248, 110));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 170));
        jPanel3.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel5.setBackground(new java.awt.Color(219, 243, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 80));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 80));
        jPanel5.setLayout(new java.awt.BorderLayout(20, 20));

        jPanel7.setBackground(new java.awt.Color(219, 243, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(504, 50));
        jPanel7.setPreferredSize(new java.awt.Dimension(504, 50));
        jPanel7.setLayout(new java.awt.GridLayout(1, 4, 12, 0));

        btnHapus.setBackground(new java.awt.Color(231, 35, 35));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/hapus.png"))); // NOI18N
        btnHapus.setText("DELETE");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setIconTextGap(10);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel7.add(btnHapus);

        btnEdit.setBackground(new java.awt.Color(245, 140, 38));
        btnEdit.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/edit.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setIconTextGap(10);
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel7.add(btnEdit);

        btnTambah.setBackground(new java.awt.Color(82, 201, 93));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/tambah.png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setIconTextGap(10);
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel7.add(btnTambah);

        btnReset.setBackground(new java.awt.Color(31, 123, 246));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/reset.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.setIconTextGap(10);
        btnReset.addActionListener(this::btnResetActionPerformed);
        jPanel7.add(btnReset);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel11.setBackground(new java.awt.Color(219, 243, 255));
        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 12, 0));

        jPanel8.setBackground(new java.awt.Color(219, 243, 255));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel2.setText(" Kode Jurusan");
        jPanel8.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tKodeJur.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jPanel8.add(tKodeJur, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(219, 243, 255));
        jPanel9.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setText(" Nama Jurusan");
        jPanel9.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tNamaJur.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        jPanel9.add(tNamaJur, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel9);

        jPanel5.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(219, 243, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));
        jPanel4.setLayout(new java.awt.CardLayout());

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJurusanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJurusan);

        jPanel4.add(jScrollPane1, "card2");

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
        String kodeJurusan = tKodeJur.getText();
        
        // Ambil input dari text field tNamaJurusan dan simpan ke variabel namaJurusan
        String namaJurusan = tNamaJur.getText();
        
        // Query SQL untuk menyisipkan data ke tabel jurusan
        String sql = "INSERT INTO jurusan(kode_jur,nama_jur) VALUES(?,?)";

        try {
            
            // Buat koneksi ke database menggunakan method konek() dari class koneksi
            Connection conn = Koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(1, kodeJurusan);
            
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(2, namaJurusan);
            
            // Jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "data berhasil disimpan!");
        } catch (SQLException sQLException) {
            
            // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
            JOptionPane.showConfirmDialog(null, "Data gagal disimpan!");
        }
        
        // Panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // Panggil method untuk mereset atau mengosongkan inputan
        reset();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
        String kodeJurusan = tKodeJur.getText();
        
        // Ambil input dari text field tnamaJurusan dan simpan ke variabel namaJurusan
        String namaJurusan = tNamaJur.getText();
        
        //Query SQL untuk mengubah data pada tabel jurusan
        String sql = "UPDATE jurusan SET nama_jur=? WHERE kode_jur=?";

        try {
            // Buat koneksi ke database menggunakan method konek() dari class koneksi
            Connection conn = Koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Isi parameter pertama (?) dengan nama jurusan
            ps.setString(1, namaJurusan);
            
            // Isi parameter kedua (?) dengan kode jurusan
            ps.setString(2, kodeJurusan);
            
            // Jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "data berhasil diubah!");
        } catch (SQLException sQLException) {
            
            // Jika terjadi kesalahan saat menyimpan data, tampilkan pesan gagal
            JOptionPane.showConfirmDialog(null, "Data gagal diubah!");
        }
        
        // Panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // Panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        // Ambil input dari text field tKodeJurusan dan simpan ke variabel kodeJurusan
        String kodeJurusan = tKodeJur.getText();
        
        // Query SQL untuk menghapus data pada tabel jurusan berdasarkan kode_jur
        String sql = "DELETE FROM jurusan WHERE kode_jur=?";

        try {
            // Query SQL untuk menghapus data pada tabel jurusan berdasarkan kode_jur
            Connection conn = Koneksi.konek();
            
            // Siapkan query SQL untuk dieksekusi dengan parameter
            PreparedStatement ps = conn.prepareStatement(sql);
            
            // Isi parameter pertama (?) dengan kode jurusan
            ps.setString(1, kodeJurusan);
            
            // Jalankan query untuk menyimpan data ke database
            ps.execute();
            
            // Tampilkan pesan bahwa data berhasil dihapus
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException sqlException) {
            
            // Jika terjadi kesalahan saat menghapus data, tampilkan pesan gagal
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }
        
        // Panggil method untuk memuat ulang data pada tabel jurusan
        load_tabel_jurusan();
        
        // Panggil method untuk mereset atau mengosongkan inputan
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblJurusanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJurusanMouseClicked
        // TODO add your handling code here:
        //ambil indeks baris yg di klik oleh pengguna di table jurusan
        int barisYangDipilih = tblJurusan.rowAtPoint(evt.getPoint());
        
        //ambil nilai dari kolom pertama (index 0) pada baris yg dipilih, yaitu 'kode_jur'
        String kodeJurusan = tblJurusan.getValueAt(barisYangDipilih, 0).toString();
        
        //ambil nilai dari kolom pertama (index 1) pada baris yg dipilih, yaitu 'nama_jur'
        String namaJurusan = tblJurusan.getValueAt(barisYangDipilih, 1).toString();
        
        //tampilan kode jurusan di textfield tKodeJur
        tKodeJur.setText(kodeJurusan);
        
        //nonaktifkan pengeditan pada textfield kode jurusan (agar tidak bisa di ubah)
        tKodeJur.setEditable(false);
        
        //tampilkan nam_jurusan di textfield tNamaJur
        tNamaJur.setText(namaJurusan);
        
    }//GEN-LAST:event_tblJurusanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JTextField tKodeJur;
    private javax.swing.JTextField tNamaJur;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables
}
