/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201029;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Al
 */
public class PanelGuru extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelGuru() {
        initComponents();
        
        //mengosongkan form input dan mengatur ulang komponen input
        reset();
        
        //memuat data dari database ke dalam tabel guru pada GUI
        load_tabel_guru();
    }
    
    //method untuk mereset form input
    void reset(){
        //kosongkan field nip
        tNIP.setText(null);
        
        //aktifkan kkembali agar NIP bisa di edit kembali
        tNIP.setEditable(true);
        
        //kosongkan field nama guru
        tNamaGuru.setText(null);
        
        //reset pilihan jenis kelamin (combo box)
        cJenisKel.setSelectedItem(null);
        
        //kosongkan field alamat
        tAlamat.setText(null);
    }
    
    //method utk memuat data dari tabel 'guru' ke dalam tabel gui (tblguru)
    void load_tabel_guru(){
        
        //membuat model tabel guru
        DefaultTableModel model = new DefaultTableModel();
        
        //menambahkan nama kolom ke dalam model tabel
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("L/P");
        model.addColumn("Alamat");
        
        
        try {
            //sql utk mengambil semua data dari tabel guru
            String sql = "SELECT * FROM guru";

            //membuka koneksi ke database
            Connection conn = Koneksi.konek();

            //membuat statement sql
            Statement st = conn.createStatement();

            //menjalankan query dan menyimpan hasilnya
            ResultSet rs = st.executeQuery(sql);

            //iterasi utk setiap baris hasil query
            while (rs.next()) {

                //mengambil nilai dari masing2 kolom
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String jenisKelamin = rs.getString("gender");
                String alamat = rs.getString("alamat");

                //menyusun data ke dalam array objek
                Object[] baris = {NIP, namaGuru, jenisKelamin, alamat};

                //menambahkan data ke model tabel
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            //menampilka pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(null, "gagal mengambil data guru!");
        }
        
        //menampilkan data model ke dalam tabel GUI
        tblGuru.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNamaGuru = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cJenisKel = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 220, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24)));
        setMinimumSize(new java.awt.Dimension(930, 590));
        setPreferredSize(new java.awt.Dimension(930, 590));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(219, 243, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(101, 202, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText("Data Guru");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 24, 0, 0));
        jPanel10.add(jLabel1);

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/Close Window.png"))); // NOI18N
        lblClose.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 24));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel10.add(lblClose);

        jPanel1.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(219, 243, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));
        jPanel6.setPreferredSize(new java.awt.Dimension(320, 606));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(219, 243, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(292, 390));

        jPanel9.setBackground(new java.awt.Color(219, 243, 255));
        jPanel9.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel2.setText(" NIP");
        jPanel9.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tNIP.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tNIP.addActionListener(this::tNIPActionPerformed);
        jPanel9.add(tNIP, java.awt.BorderLayout.CENTER);

        jPanel11.setBackground(new java.awt.Color(219, 243, 255));
        jPanel11.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setText(" Nama");
        jPanel11.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tNamaGuru.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tNamaGuru.addActionListener(this::tNamaGuruActionPerformed);
        jPanel11.add(tNamaGuru, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(219, 243, 255));
        jPanel12.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel4.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel4.setText(" Jenis Kelamin");
        jPanel12.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        cJenisKel.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        cJenisKel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - laki", "Perempuan" }));
        jPanel12.add(cJenisKel, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(219, 243, 255));
        jPanel13.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel5.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel5.setText(" Alamat");
        jPanel13.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        tAlamat.setColumns(20);
        tAlamat.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        jPanel13.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(219, 243, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 24, 24));
        jPanel4.setPreferredSize(new java.awt.Dimension(576, 75));
        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 12, 0));

        btnHapus.setBackground(new java.awt.Color(231, 35, 35));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/hapus.png"))); // NOI18N
        btnHapus.setText("DELETE");
        btnHapus.setIconTextGap(10);
        btnHapus.addActionListener(this::btnHapusActionPerformed);
        jPanel4.add(btnHapus);

        btnEdit.setBackground(new java.awt.Color(245, 140, 38));
        btnEdit.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/edit.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setIconTextGap(10);
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel4.add(btnEdit);

        btnTambah.setBackground(new java.awt.Color(82, 201, 93));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/tambah.png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setIconTextGap(10);
        btnTambah.addActionListener(this::btnTambahActionPerformed);
        jPanel4.add(btnTambah);

        jButton4.setBackground(new java.awt.Color(31, 123, 246));
        jButton4.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/reset.png"))); // NOI18N
        jButton4.setText("RESET");
        jButton4.setIconTextGap(10);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel4.add(jButton4);

        jPanel5.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel7.setBackground(new java.awt.Color(219, 243, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 0, 24, 24));
        jPanel7.setLayout(new java.awt.CardLayout());

        tblGuru.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        jPanel7.add(jScrollPane1, "card2");

        jPanel5.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIPActionPerformed

    private void tNamaGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaGuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaGuruActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // TODO add your handling code here:
        // Mengambil indeks baris yang diklik oleh pengguna di tabel tblGuru
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        
     
        // Mengambil nilai NIP dari kolom pertama (indeks 0) pada baris yang dipilih
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();

        // Mengambil nilai nama guru dari kolom kedua (indeks 1) pada baris yang dipilih
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();

        // Mengambil nilai jenis kelamin dari kolom ketiga (indeks 2) pada baris yang dipilih
        String jenisKelamin = tblGuru.getValueAt(barisYangDipilih, 2).toString();

        ////// Mengambil object alamat dari kolom keempat (indeks 3) pada baris yang dipilih
        Object alamatObj = tblGuru.getValueAt(barisYangDipilih, 3);
        
        ////// Mengonversi objek menjadi string, jika null maka hasilnya null atau string kosong
        String alamat = (alamatObj != null) ? alamatObj.toString() : "";
        

        // Menampilkan nilai NIP ke dalam text field tNIP
        tNIP.setText(NIP);

        // Menonaktifkan field tNIP agar tidak bisa diedit (karena NIP bersifat unik dan tidak boleh diubah)
        tNIP.setEditable(false);

        // Menampilkan nama guru ke dalam text field tNamaGuru
        tNamaGuru.setText(namaGuru);

        // Menampilkan alamat ke dalam text field tAlamat
        tAlamat.setText(alamat);

        // Mengecek isi nilai jenis kelamin dan menyesuaikan pilihan pada combo box cJenisKelamin
        switch (jenisKelamin) {
            // Jika nilai jenis kelamin "L", set pilihan combo box ke "Laki - laki"
            case "L":
                cJenisKel.setSelectedItem("Laki - laki");
                break;

            // Jika nilai jenis kelamin "P", set pilihan combo box ke "Perempuan"
            case "P":
                cJenisKel.setSelectedItem("Perempuan");
                break;

            // Jika nilainya bukan "L" atau "P", kosongkan pilihan combo box
            default:
                cJenisKel.setSelectedItem(null);
                break;
        }
        
    }//GEN-LAST:event_tblGuruMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:

        // Mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();

        // Mengambil input nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();

        // Mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKel.getSelectedItem().toString();

        // Mengambil input alamat dari text field tAlamat
        String alamat = tAlamat.getText();

        // Menyiapkan variabel jK (jenis kelamin dalam format singkatan "L" atau "P")
        String jK = null;

        // Mengubah nilai jenisKelamin dari label menjadi format singkatan yang disimpan di database
        switch (jenisKelamin) {
            case "Laki - laki":
                jK = "L";
                break;

            case "Perempuan":
                jK = "P";
                break;

            default:
                jK = null;
                break;
        }

        // Menyusun perintah SQL untuk menyisipkan data guru ke dalam tabel guru
        String sql = "INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES(?,?,?,?)";

        try {

            // Membuka koneksi ke database menggunakan method konek()
            Connection conn = Koneksi.konek();

            // Mempersiapkan query SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi parameter pertama dengan NIP
            ps.setString(1, NIP);

            // Mengisi parameter kedua dengan nama guru
            ps.setString(2, namaGuru);

            // Mengisi parameter ketiga dengan jenis kelamin (L atau P)
            ps.setString(3, jK);

            // Mengisi parameter keempat dengan alamat
            ps.setString(4, alamat);

            // Menjalankan perintah INSERT untuk menyimpan data ke database
            ps.execute();

            // Menampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");

        } catch (SQLException sqLException) {

            // Menampilkan pesan jika terjadi kesalahan saat menyimpan data
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        }

        // Memuat ulang data guru di tabel tampilan
        load_tabel_guru();

        // Mereset semua input agar kosong kembali
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        // Mengambil nilai NIP dari text field tNIP
        String NIP = tNIP.getText();

        // Mengambil nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();

        // Mengambil item yang dipilih dari combo box jenis kelamin
        String jenisKelamin = cJenisKel.getSelectedItem().toString();

        // Mengambil alamat dari text field tAlamat
        String alamat = tAlamat.getText();

        // Menyiapkan variabel untuk menyimpan singkatan jenis kelamin ("L" atau "P")
        String jK = null;

        // Mengubah label jenis kelamin menjadi singkatan yang sesuai dengan format database
        switch (jenisKelamin) {
            case "Laki - laki":
                jK = "L";
                break;

            case "Perempuan":
                jK = "P";
                break;

            default:
                jK = null;
                break;
        }

        // Menyusun perintah SQL untuk memperbarui data guru berdasarkan NIP
        String sql = "UPDATE guru SET nama_guru=?, gender=?, alamat=? WHERE nip=?";

        try {

            // Membuka koneksi ke database
            Connection conn = Koneksi.konek();

            // Mempersiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi parameter pertama (?) dengan nama guru
            ps.setString(1, namaGuru);

            // Mengisi parameter kedua (?) dengan jenis kelamin ("L"/"P")
            ps.setString(2, jK);

            // Mengisi parameter ketiga (?) dengan alamat
            ps.setString(3, alamat);

            // Mengisi parameter keempat (?) dengan NIP sebagai identitas data yang akan diubah
            ps.setString(4, NIP);

            // Menjalankan perintah UPDATE
            ps.execute();

            // Menampilkan pesan bahwa data berhasil diubah
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");

        } catch (SQLException sqLException) {

            // Menampilkan pesan jika proses update gagal
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
        }

        // Memuat ulang tabel guru untuk menampilkan data terbaru
        load_tabel_guru();

        // Mereset/mengosongkan form input
        reset();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:

        // Mengambil nilai NIP dari text field tNIP
        String NIP = tNIP.getText();

        // Menyusun perintah SQL untuk menghapus data berdasarkan NIP
        String sql = "DELETE FROM guru WHERE nip=?";

        try {

            // Membuka koneksi ke database
            Connection conn = Koneksi.konek();

            // Menyiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi parameter pertama (?) dengan nilai NIP
            ps.setString(1, NIP);

            // Menjalankan perintah DELETE untuk menghapus data dari database
            ps.execute();

            // Menampilkan pesan jika data berhasil dihapus
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");

        } catch (SQLException sqLException) {

            // Menampilkan pesan jika terjadi kesalahan saat proses penghapusan
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        }

        // Memuat ulang data pada tabel guru setelah penghapusan
        load_tabel_guru();

        // Mereset atau mengosongkan form input
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        reset();
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cJenisKel;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}
