/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201029;

/**
 *
 * @author Al
 */
public class PanelJurusan extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelJurusan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tKodeJur = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNamaJur = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJurusan = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 220, 255));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24)));
        setMinimumSize(new java.awt.Dimension(930, 590));
        setPreferredSize(new java.awt.Dimension(930, 590));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(219, 243, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(101, 202, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Plus Jakarta Sans ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText("Data Jurusan");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 24, 0, 0));
        jPanel10.add(jLabel1);

        jPanel1.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(219, 243, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 0, 24));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 160));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(219, 243, 255));
        jPanel5.setMinimumSize(new java.awt.Dimension(200, 80));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 80));

        jPanel7.setLayout(new java.awt.GridLayout(1, 4, 12, 0));

        btnEdit.setBackground(new java.awt.Color(245, 140, 38));
        btnEdit.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/edit.png"))); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.setIconTextGap(10);
        jPanel7.add(btnEdit);

        btnTambah.setBackground(new java.awt.Color(82, 201, 93));
        btnTambah.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/tambah.png"))); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setIconTextGap(10);
        jPanel7.add(btnTambah);

        btnHapus.setBackground(new java.awt.Color(231, 35, 35));
        btnHapus.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/hapus.png"))); // NOI18N
        btnHapus.setText("DELETE");
        btnHapus.setIconTextGap(10);
        jPanel7.add(btnHapus);

        btnReset.setBackground(new java.awt.Color(31, 123, 246));
        btnReset.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201029/img/reset.png"))); // NOI18N
        btnReset.setText("RESET");
        btnReset.setIconTextGap(10);
        jPanel7.add(btnReset);

        jPanel11.setBackground(new java.awt.Color(219, 243, 255));
        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 12, 0));

        jPanel8.setBackground(new java.awt.Color(219, 243, 255));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel2.setText(" Kode Jurusan");
        jPanel8.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        tKodeJur.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tKodeJur.setText("jTextField1");
        jPanel8.add(tKodeJur, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(219, 243, 255));
        jPanel9.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel3.setFont(new java.awt.Font("Plus Jakarta Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setText(" Nama Jurusan");
        jPanel9.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        tNamaJur.setFont(new java.awt.Font("Plus Jakarta Sans", 0, 14)); // NOI18N
        tNamaJur.setText("jTextField1");
        jPanel9.add(tNamaJur, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(219, 243, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(24, 24, 24, 24));
        jPanel4.setLayout(new java.awt.CardLayout());

        tblJurusan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJurusan);

        jPanel4.add(jScrollPane1, "card2");

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tKodeJur;
    private javax.swing.JTextField tNamaJur;
    private javax.swing.JTable tblJurusan;
    // End of variables declaration//GEN-END:variables
}
